{% set version = "0.2.7" %}
{% set sha256 = "9d711a673ce90243d9f62be099c4c85d7d2dff334673f4796e63b1b44ab29a92" %}

package:
  name: ipypivot
  version: {{ version }}

source:
  fn: ipypivot-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipypivot/ipypivot-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=7.0.0,<8.0
        - traitlets >=4.3.0
        - traittypes >=0.0.6
        - numpy >=1.10.4
        - pandas

test:
    imports:
        - ipypivot

about:
  home: https://github.com/PierreMarion23/ipypivot
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'A jupyter widget (or ipywidget) wrapping the very convenient pivotTable.js library'

  description: |
    This is a jupyter widget (or ipywidget) wrapping the very convenient pivotTable.js library.
    It enables to display and embed a pivotTable in a Jupyter notebook in a few Python lines.
  dev_url: https://github.com/PierreMarion23/ipypivot

extra:
  recipe-maintainers:
    - PierreMarion23
    - ocoudray
    - oscar6echo
